language: ruby
addons:
    postgresql: 9.6
services:
    - postgresql
    - redis-server
before_script:
  - psql -c 'create database crowdbreaks_test;' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake rspec
branches:
  only:
    - master
