language: ruby
sudo: required

addons:
  postgresql: "9.4"
  chrome: stable

before_install:
  - "export DISPLAY=99:0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - gem update --system
  - gem install bundler

services:
  - postgresql
  - redis-server

before_script:
  - psql -c 'create database crowdbreaks_test;' -U postgres
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec --exclude-pattern "features/*_spec.rb"

branches:
  only:
    - master
