language: ruby
addons:
    postgresql: "9.4"
services:
    - postgresql
    - redis-server
before_script:
  - psql -c 'create database crowdbreaks_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
branches:
  only:
    - master
