version: "3.0"
services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - webpack-dev-server
    environment:
      - POSTGRES_HOST=db
      - WEBPACKER_DEV_SERVER_HOST=webpack-dev-server
      - REDIS_URL=redis://redis:6379
    tty: true
    stdin_open: true

  webpack-dev-server:
    build: .
    container_name: webpack
    command: ./bin/webpack-dev-server
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    volumes:
      - $PWD:/app:delegated
      - bundle_cache:/usr/local/bundle:cached
      - node_modules:/app/node_modules:cached
    ports:
      - "3035:3035"

  db:
    image: postgres:10.15
    container_name: db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:cached
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:6.0.9
    container_name: redis
    volumes:
      - redis_data:/data:cached

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
    - "4444:4444"

  sidekiq:
    build: .
    container_name: sidekiq
    command: bundle exec sidekiq -q default -q mailers
    environment:
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379
    volumes:
      - $PWD:/app:delegated
      - bundle_cache:/usr/local/bundle:cached
      - node_modules:/app/node_modules:cached
    depends_on:
      - db
      - redis

volumes:
  db_data:
  bundle_cache:
  node_modules:
  redis_data:
